server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
  hibernate:
    ddl-auto: update
    jwt:
      secret: javamaster

  flyway:
    schemas: migrations
    baseline: true
    datasources:
      default:
        locations: classpath:db/migrations


