server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
  hibernate:
    ddl-auto: update

    jwt:
      expiration: 1296000
      secret: javamaster

  flyway:
    schemas: public
    baselineOnMigrate: true
    datasources:
      default:
        locations: classpath:db/migrations

  spring:
    servlet:
      multipart:
        enabled: true
          file-size-threshold=2KB
          max-file-size=200MB
          max-request-size=215MB
          file.upload-dir=C:\\Users\Alina\uploads



