server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
  hibernate:
    ddl-auto: update
    spring:
      security:
        jwt:
          token:
            secret-key: secret-key
            expire-length: 300000
  flyway:
    datasources:
      default:
        locations: classpath:databasemigrations
  endpoints:
    flyway:
      enabled: true
      sensitive: false
